In [16]:
import numpy as np
from datascience import *

# 1) Create an array containg 4 string elements: your first name, last name, birth state and favorite color.

In [17]:
Info=["Chloe","Fleck","Indiana","Blue"]
Info

['Chloe', 'Fleck', 'Indiana', 'Blue']

# a. use numpy function to make all elements uppercase

In [22]:
np.char.upper(Info)

array(['CHLOE', 'FLECK', 'INDIANA', 'BLUE'], dtype='<U7')

# b. use numpy function to count the number of times a appears in each element of the array

In [23]:
np.char.count(Info,"a")

array([0, 0, 2, 0])

# c. Use numpy function to find the length of each element in the array

In [56]:
sizes=[]
for i in Info:
    sizes.append(len(i))
print (sizes)

[5, 5, 7, 4]


# 2) Create an array containing every other odd number starting with 1 and ending with 41

In [59]:
my_array=np.arange(1,42,4)
my_array

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41])

# a. use numpy to find the sum and the product of the elements in this array

In [62]:
floated_array=my_array.astype(float)
floated_array

array([ 1.,  5.,  9., 13., 17., 21., 25., 29., 33., 37., 41.])

In [63]:
np.sum(floated_array)

231.0

In [64]:
np.prod(floated_array)

7579867420125.0

# b. use numpy to find the natural log of each element

In [65]:
np.log(floated_array)

array([0.        , 1.60943791, 2.19722458, 2.56494936, 2.83321334,
       3.04452244, 3.21887582, 3.36729583, 3.49650756, 3.61091791,
       3.71357207])